In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder

sns.set_theme()
sns.set_palette("deep")
RANDOM_SEED = 42

In [ ]:
with open('19901999.csv', 'r') as f:
  master = [] #list to have relevant features from the resale flat price dataset
  header = next(f)
  for row in f:
    lis = row.strip().split(',')
    lis[0] = lis[0][0:4] + lis[0][5:] #processing string with '-' into an integer value
    line = [float(lis[0]), lis[2], float(lis[6]), lis[7], float(lis[8]), float(lis[9])]
    master.append(line)

month, flat_type, floor_area_sqm, flat_model, lease_commence_date, resale_price = 0,1,2,3,4,5

#removing records with inaccurate flat models that are duplicated from flat types

#for row in master:
  #print(row)
enc = OrdinalEncoder()
X = [['1 ROOM'], ['2 ROOM'], ['3 ROOM'], ['4 ROOM'], ['5 ROOM'], ['EXECUTIVE'], ['MULTI GENERATION']]
X_2 = [['SIMPLIFIED'], ['IMPROVED'], ['MODEL A'], ['APARTMENT'], ['NEW GENERATION'], ['STANDARD'], ['MAISONETTE'], ['MODEL A-MAISONETTE'], ['TERRACE'], ['IMPROVED-MAISONETTE'], ['PREMIUM APARTMENT'], ['MULTI GENERATION'], ['2-ROOM']]
# for row in master:
#   if [row[flat_model]] not in X_2:
#     print(row)

#print(master)

enc.fit(X)
result = enc.transform([[row[flat_type]] for row in master])
enc.fit(X_2)
result2 = enc.transform([[row[flat_model]] for row in master])
for row in range(len(master)):
  master[row][flat_type] = result[row][0]
  master[row][flat_model] = result2[row][0]

data = np.array(master)

print(data)

[[1.99001e+05 0.00000e+00 3.10000e+01 2.00000e+00 1.97700e+03 9.00000e+03]
 [1.99001e+05 0.00000e+00 3.10000e+01 2.00000e+00 1.97700e+03 6.00000e+03]
 [1.99001e+05 0.00000e+00 3.10000e+01 2.00000e+00 1.97700e+03 8.00000e+03]
 ...
 [1.99912e+05 5.00000e+00 1.46000e+02 4.00000e+00 1.98800e+03 4.69000e+05]
 [1.99912e+05 5.00000e+00 1.46000e+02 4.00000e+00 1.98800e+03 4.40000e+05]
 [1.99912e+05 5.00000e+00 1.45000e+02 4.00000e+00 1.98800e+03 4.84000e+05]]


In [ ]:
import requests

collection_id = 189
url = "https://api-production.data.gov.sg/v2/public/api/collections/{}/metadata".format(collection_id)

response = requests.get(url)
#print(response.json())

for row in response:
  print(row)


b'{"code":0,"data":{"collectionMetadata":{"collectionId":"189","createdAt":"2015-09-22T15:05:30+08:00","name":"Resale Flat Prices"'
b',"description":"Resale transacted prices. \\r\\nPrior to March 2012, data is based on date of approval for the resale transactions'
b'.  \\r\\nFor March 2012 onwards, the data is based on date of registration for the resale transactions.","lastUpdatedAt":"2025-04-'
b'18T02:09:18+08:00","coverageStart":"1990-01-01T08:00:00+08:00","coverageEnd":"2024-04-08T00:00:00+08:00","frequency":"monthly","'
b'sources":["Housing & Development Board"],"managedBy":"Housing & Development Board","childDatasets":["d_8b84c4ee58e3cfc0ece0d773c'
b'8ca6abc","d_43f493c6c50d54243cc1eab0df142d6a","d_2d5ff9ea31397b66239f245f57751537","d_ebc5ab87086db484f88045b47411ebc5","d_ea9ed'
b'51da2787afaf8e51f827c304208"]}},"errorMsg":""}'


In [ ]:
month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price

0, 2, 6, 7, 8, 9

In [ ]:
import csv
months = [['01', '02', '03'], ['04', '05', '06'], ['07', '08', '09'], ['10', '11', '12']]
dic = {}
for i in range(1990, 2025):
  for j in range(1, 5):
    dic[str(i)+str(j)+'Q'] = []
    for m in months[j-1]:
      dic[str(i)+str(j)+'Q'] += [float(str(i)+m)]

print(dic)

finaldic = {}

with open('UnemploymentRateEndOfPeriodQuarterlySeasonallyAdjusted.csv', 'r') as f:
  master = []
  for row in f:
    row = row.strip().split(',')
    master.append(row[1:]) #removing the titles total unemployment rate, resident unemployment rate
  master = master[:2] #removing resident and citize unemployment rate
  master[1] = master[1][1:] #removing the title ' (SA)"'
for item in master[0]:
  for row in dic:
    if item == row:
      for i in dic[row]:
        finaldic[i] = float(master[1][master[0].index(item)])

print(finaldic)

{'19901Q': [199001.0, 199002.0, 199003.0], '19902Q': [199004.0, 199005.0, 199006.0], '19903Q': [199007.0, 199008.0, 199009.0], '19904Q': [199010.0, 199011.0, 199012.0], '19911Q': [199101.0, 199102.0, 199103.0], '19912Q': [199104.0, 199105.0, 199106.0], '19913Q': [199107.0, 199108.0, 199109.0], '19914Q': [199110.0, 199111.0, 199112.0], '19921Q': [199201.0, 199202.0, 199203.0], '19922Q': [199204.0, 199205.0, 199206.0], '19923Q': [199207.0, 199208.0, 199209.0], '19924Q': [199210.0, 199211.0, 199212.0], '19931Q': [199301.0, 199302.0, 199303.0], '19932Q': [199304.0, 199305.0, 199306.0], '19933Q': [199307.0, 199308.0, 199309.0], '19934Q': [199310.0, 199311.0, 199312.0], '19941Q': [199401.0, 199402.0, 199403.0], '19942Q': [199404.0, 199405.0, 199406.0], '19943Q': [199407.0, 199408.0, 199409.0], '19944Q': [199410.0, 199411.0, 199412.0], '19951Q': [199501.0, 199502.0, 199503.0], '19952Q': [199504.0, 199505.0, 199506.0], '19953Q': [199507.0, 199508.0, 199509.0], '19954Q': [199510.0, 199511.0, 19